from decouple import config

TOKEN = config("TOKEN")
CHATBOT_KEY = config("CHATBOT_KEY")

FIREBASE_TYPE = config("FIREBASE_TYPE")
FIREBASE_PROJECT_ID = config("FIREBASE_PROJECT_ID")
FIREBASE_PRIVATE_KEY_ID = config("FIREBASE_PRIVATE_KEY_ID")
FIREBASE_PRIVATE_KEY = config("FIREBASE_PRIVATE_KEY")
FIREBASE_CLIENT_EMAIL = config("FIREBASE_CLIENT_EMAIL")
FIREBASE_CLIENT_ID = config("FIREBASE_CLIENT_ID")
FIREBASE_AUTH_URI = config("FIREBASE_AUTH_URI")
FIREBASE_TOKEN_URI = config("FIREBASE_TOKEN_URI")
FIREBASE_AUTH_PROVIDER_X509_CERT_URL = config("FIREBASE_AUTH_PROVIDER_X509_CERT_URL")
FIREBASE_CLIENT_X509_CERT_URL = config("FIREBASE_CLIENT_X509_CERT_URL")
