from decouple import config

TOKEN = config("TOKEN")
PLACE_API_KEY = config("PLACE_API_KEY")
RAPID_API_KEY = config("RAPID_API_KEY")
NASA_API_KEY = config("NASA_API_KEY")
LOCAL = False if config("LOCAL").lower() == "false" else True
TESSERACT_PATH = config("TESSERACT_PATH")

FIREBASE_TYPE = config("FIREBASE_TYPE")
FIREBASE_PROJECT_ID = config("FIREBASE_PROJECT_ID")
FIREBASE_PRIVATE_KEY_ID = config("FIREBASE_PRIVATE_KEY_ID")
FIREBASE_PRIVATE_KEY = config("FIREBASE_PRIVATE_KEY").replace("\\n", "\n")
FIREBASE_CLIENT_EMAIL = config("FIREBASE_CLIENT_EMAIL")
FIREBASE_CLIENT_ID = config("FIREBASE_CLIENT_ID")
FIREBASE_AUTH_URI = config("FIREBASE_AUTH_URI")
FIREBASE_TOKEN_URI = config("FIREBASE_TOKEN_URI")
FIREBASE_AUTH_PROVIDER_X509_CERT_URL = config("FIREBASE_AUTH_PROVIDER_X509_CERT_URL")
FIREBASE_CLIENT_X509_CERT_URL = config("FIREBASE_CLIENT_X509_CERT_URL")
FIREBASE_DATABASE_URL = config("FIREBASE_DATABASE_URL")

GOOGLE_SEARCH_API_KEY = config("GOOGLE_SEARCH_API_KEY")
GOOGLE_SEARCH_ENGINE_ID = config("GOOGLE_SEARCH_ENGINE_ID")
